//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPastas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class seg_rol_operacion
    {
        public decimal id { get; set; }
        public Nullable<decimal> rol_id { get; set; }
        public Nullable<decimal> operacion_id { get; set; }
        public Nullable<System.DateTime> fecha_alta { get; set; }
    
        public virtual seg_operacion seg_operacion { get; set; }
        public virtual seg_rol seg_rol { get; set; }
    }
}
