//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPastas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class seg_rol
    {
        public seg_rol()
        {
            this.seg_rol_operacion = new HashSet<seg_rol_operacion>();
            this.seg_usuario = new HashSet<seg_usuario>();
        }
    
        public decimal id { get; set; }
        public string nombre { get; set; }
        public Nullable<System.DateTime> fecha_alta { get; set; }
    
        public virtual ICollection<seg_rol_operacion> seg_rol_operacion { get; set; }
        public virtual ICollection<seg_usuario> seg_usuario { get; set; }
    }
}
