//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPastas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class seg_operacion
    {
        public seg_operacion()
        {
            this.seg_rol_operacion = new HashSet<seg_rol_operacion>();
        }
    
        public decimal id { get; set; }
        public string nombre { get; set; }
        public Nullable<int> modulo_id { get; set; }
        public Nullable<System.DateTime> fecha_alta { get; set; }
    
        public virtual seg_modulo seg_modulo { get; set; }
        public virtual ICollection<seg_rol_operacion> seg_rol_operacion { get; set; }
    }
}
